using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Reflection;
using System.Text;
using MvvmUnity.Core;
using MvvmUnity.Unity;
using TMPro;
using UnityEditor;
using UnityEngine;
using UnityEngine.UI;

namespace MvvmUnity.Editor
{
    [InitializeOnLoad]
    public static class BindingCodeGenerator
    {
        private const string GeneratedOwner = "// Generated by MvvmUnity.";
        private const string GeneratedSuffix = ".Bindings.g.cs";

        static BindingCodeGenerator()
        {
            EditorApplication.delayCall += Rebuild;
        }

        [MenuItem("Tools/MVVM/Rebuild Generated Bindings")]
        public static void Rebuild()
        {
            if (EditorApplication.isCompiling || EditorApplication.isUpdating)
            {
                EditorApplication.delayCall += Rebuild;
                return;
            }

            var scriptPaths = ScriptPaths();
            var expected = new HashSet<string>(StringComparer.OrdinalIgnoreCase);
            var changed = false;
            foreach (var viewType in TypeCache.GetTypesWithAttribute<GenerateBindingsAttribute>())
            {
                if (!TryGeneratedPath(viewType, scriptPaths, out var path))
                    continue;

                // Файл остаётся за видом даже когда генерация не удалась: удалить его —
                // значит сломать компиляцию, а без компиляции генератор больше не запустится.
                expected.Add(path);
                if (TrySource(viewType, out var source))
                    changed |= WriteWhenChanged(path, source);
            }

            changed |= RemoveOrphans(expected);
            if (changed)
                AssetDatabase.Refresh();
        }

        [MenuItem("Tools/MVVM/Clean Generated Bindings")]
        public static void Clean()
        {
            var changed = false;
            foreach (var path in GeneratedPaths())
            {
                if (Owned(path))
                    changed |= AssetDatabase.DeleteAsset(path);
            }

            if (changed)
                AssetDatabase.Refresh();
        }

        private static bool TryGeneratedPath(
            Type viewType,
            IReadOnlyDictionary<Type, string> scriptPaths,
            out string path)
        {
            path = string.Empty;
            if (!ValidViewType(viewType))
                return false;
            if (!scriptPaths.TryGetValue(viewType, out var sourcePath))
            {
                Debug.LogError($"MVVM source script was not found for {viewType.FullName}");
                return false;
            }

            var generatedFolder = Path.Combine(Path.GetDirectoryName(sourcePath), "Generated");
            var safeName = viewType.FullName.Replace('+', '.');
            path = Path.Combine(generatedFolder, safeName + GeneratedSuffix).Replace('\\', '/');
            return true;
        }

        private static bool TrySource(Type viewType, out string source)
        {
            source = string.Empty;
            var generation = viewType.GetCustomAttribute<GenerateBindingsAttribute>();
            if (generation == null)
                return false;

            var inheritedViewModel = InheritedViewModel(viewType);
            var viewModelType = generation.ViewModelType ?? inheritedViewModel;
            if (viewModelType == null)
            {
                Debug.LogError($"MVVM cannot infer ViewModel for {viewType.FullName}. Inherit MvvmView<T> or pass typeof(T).");
                return false;
            }
            if (inheritedViewModel != null && inheritedViewModel != viewModelType)
            {
                Debug.LogError($"MVVM ViewModel mismatch in {viewType.FullName}: base uses {inheritedViewModel.FullName}, attribute uses {viewModelType.FullName}.");
                return false;
            }

            var bindings = Bindings(viewType, viewModelType, generation.Conventions).ToArray();
            var observations = Observations(viewType).ToArray();
            if (bindings.Length == 0 && observations.Length == 0)
            {
                Debug.LogError($"MVVM view has no convention bindings, [Bind] fields or [Observe] methods: {viewType.FullName}");
                return false;
            }
            if (!TryResolveBindings(viewType, viewModelType, bindings, out var resolvedBindings) ||
                !TryResolveObservations(viewType, viewModelType, observations, out var resolvedObservations))
                return false;

            source = Source(viewType, viewModelType, resolvedBindings, resolvedObservations);
            return true;
        }

        private static bool ValidViewType(Type viewType)
        {
            if (!viewType.IsNested && !viewType.IsGenericType)
                return true;
            Debug.LogError($"MVVM code generation supports only non-nested, non-generic views: {viewType.FullName}");
            return false;
        }

        private static Type InheritedViewModel(Type viewType)
        {
            var current = viewType;
            while (current != null)
            {
                if (current.IsGenericType && current.GetGenericTypeDefinition() == typeof(MvvmView<>))
                    return current.GetGenericArguments()[0];
                current = current.BaseType;
            }

            return null;
        }

        private static IReadOnlyDictionary<Type, string> ScriptPaths()
        {
            var paths = new Dictionary<Type, string>();
            foreach (var guid in AssetDatabase.FindAssets("t:MonoScript"))
            {
                var candidate = AssetDatabase.GUIDToAssetPath(guid);
                if (string.IsNullOrEmpty(candidate))
                    continue;
                var script = AssetDatabase.LoadAssetAtPath<MonoScript>(candidate);
                var type = script != null ? script.GetClass() : null;
                if (type == null || paths.ContainsKey(type))
                    continue;
                paths.Add(type, candidate);
            }

            return paths;
        }

        private static IEnumerable<(FieldInfo Field, BindAttribute Attribute)> Bindings(
            Type viewType,
            Type viewModelType,
            bool conventions)
        {
            var fields = viewType
                .GetFields(BindingFlags.Instance | BindingFlags.Public | BindingFlags.NonPublic | BindingFlags.DeclaredOnly)
                .OrderBy(field => field.MetadataToken);
            foreach (var field in fields)
            {
                var explicitBindings = field.GetCustomAttributes<BindAttribute>().ToArray();
                if (explicitBindings.Length > 0)
                {
                    foreach (var binding in explicitBindings)
                        yield return (field, binding);
                    continue;
                }

                if (!conventions ||
                    field.GetCustomAttribute<SerializeField>() == null ||
                    field.GetCustomAttribute<IgnoreBindingAttribute>() != null)
                    continue;
                var source = ConventionSource(field.Name);
                if (source.Length == 0 || PublicSourceType(viewModelType, source) == null)
                    continue;
                yield return (field, new BindAttribute(source));
            }
        }

        private static IEnumerable<(MethodInfo Method, ObserveAttribute Attribute)> Observations(Type viewType)
        {
            return viewType
                .GetMethods(BindingFlags.Instance | BindingFlags.Public | BindingFlags.NonPublic | BindingFlags.DeclaredOnly)
                .OrderBy(method => method.MetadataToken)
                .SelectMany(method => method
                    .GetCustomAttributes<ObserveAttribute>()
                    .Select(attribute => (method, attribute)));
        }

        /// Цель биндинга вычисляется один раз: раньше её считали при проверке
        /// и повторно при генерации, молча игнорируя ошибку во второй раз.
        private static bool TryResolveBindings(
            Type viewType,
            Type viewModelType,
            IReadOnlyCollection<(FieldInfo Field, BindAttribute Attribute)> bindings,
            out IReadOnlyCollection<(FieldInfo Field, BindAttribute Attribute, BindingTarget Target)> resolved)
        {
            var list = new List<(FieldInfo, BindAttribute, BindingTarget)>();
            resolved = list;
            foreach (var binding in bindings)
            {
                if (TryBindingTarget(binding.Field, binding.Attribute, viewModelType, out var target, out var error))
                {
                    list.Add((binding.Field, binding.Attribute, target));
                    continue;
                }

                Debug.LogError($"MVVM binding error in {viewType.FullName}.{binding.Field.Name}: {error}");
                return false;
            }

            return true;
        }

        private static bool TryResolveObservations(
            Type viewType,
            Type viewModelType,
            IReadOnlyCollection<(MethodInfo Method, ObserveAttribute Attribute)> observations,
            out IReadOnlyCollection<(MethodInfo Method, string Source)> resolved)
        {
            var list = new List<(MethodInfo, string)>();
            resolved = list;
            foreach (var observation in observations)
            {
                var source = observation.Attribute.Source;
                if (source.Length == 0 &&
                    !TryObservationSource(observation.Method, viewModelType, out source, out var inferenceError))
                {
                    Debug.LogError($"MVVM observation error in {viewType.FullName}.{observation.Method.Name}: {inferenceError}");
                    return false;
                }
                if (ValidObservation(observation.Method, source, viewModelType, out var error))
                {
                    list.Add((observation.Method, source));
                    continue;
                }
                Debug.LogError($"MVVM observation error in {viewType.FullName}.{observation.Method.Name}: {error}");
                return false;
            }

            return true;
        }

        private static bool TryBindingTarget(
            FieldInfo field,
            BindAttribute attribute,
            Type viewModelType,
            out BindingTarget target,
            out string error)
        {
            var sourceType = PublicSourceType(viewModelType, attribute.Source);
            target = attribute.Target;
            if (sourceType == null)
            {
                error = $"public source '{attribute.Source}' was not found on {viewModelType.FullName}";
                return false;
            }
            if (target == BindingTarget.Auto && !InferTarget(field.FieldType, sourceType, out target))
            {
                error = $"cannot infer a binding for {field.FieldType.Name} from {sourceType.Name}; specify BindingTarget explicitly";
                return false;
            }
            if (!ValidTarget(field.FieldType, sourceType, target))
            {
                error = $"{field.FieldType.Name} cannot bind {sourceType.Name} as {target}";
                return false;
            }

            error = string.Empty;
            return true;
        }

        private static bool ValidObservation(
            MethodInfo method,
            string source,
            Type viewModelType,
            out string error)
        {
            if (method.IsStatic || method.IsGenericMethod || method.ReturnType != typeof(void))
            {
                error = "observer must be a non-static, non-generic void method";
                return false;
            }
            var parameters = method.GetParameters();
            if (parameters.Length != 1)
            {
                error = "observer must accept exactly one state argument";
                return false;
            }
            var sourceType = PublicSourceType(viewModelType, source);
            if (sourceType == null)
            {
                error = $"public source '{source}' was not found on {viewModelType.FullName}";
                return false;
            }
            if (!ObservableOf(sourceType, typeof(IReadOnlyObservableValue<>), parameters[0].ParameterType))
            {
                error = $"{sourceType.Name} does not publish {parameters[0].ParameterType.Name}";
                return false;
            }

            error = string.Empty;
            return true;
        }

        private static bool TryObservationSource(
            MethodInfo method,
            Type viewModelType,
            out string source,
            out string error)
        {
            source = string.Empty;
            var parameters = method.GetParameters();
            if (method.IsStatic || method.IsGenericMethod || method.ReturnType != typeof(void) || parameters.Length != 1)
            {
                error = "observer source inference requires a non-static, non-generic void method with one argument";
                return false;
            }

            var valueType = parameters[0].ParameterType;
            var candidates = viewModelType
                .GetProperties(BindingFlags.Instance | BindingFlags.Public)
                .Where(property => property.GetMethod != null &&
                    ObservableOf(property.PropertyType, typeof(IReadOnlyObservableValue<>), valueType))
                .Select(property => property.Name)
                .Concat(viewModelType
                    .GetFields(BindingFlags.Instance | BindingFlags.Public)
                    .Where(field => ObservableOf(field.FieldType, typeof(IReadOnlyObservableValue<>), valueType))
                    .Select(field => field.Name))
                .Distinct()
                .ToArray();
            if (candidates.Length == 1)
            {
                source = candidates[0];
                error = string.Empty;
                return true;
            }

            error = candidates.Length == 0
                ? $"no public observable publishes {valueType.Name}; specify [Observe(nameof(...))]"
                : $"multiple public observables publish {valueType.Name}: {string.Join(", ", candidates)}; specify [Observe(nameof(...))]";
            return false;
        }

        private static string ConventionSource(string fieldName)
        {
            var name = fieldName.TrimStart('_');
            if (name.Length == 0)
                return string.Empty;
            return char.ToUpperInvariant(name[0]) + name.Substring(1);
        }

        private static Type PublicSourceType(Type viewModelType, string name)
        {
            var property = viewModelType.GetProperty(name, BindingFlags.Instance | BindingFlags.Public);
            if (property != null && property.GetMethod != null)
                return property.PropertyType;
            var field = viewModelType.GetField(name, BindingFlags.Instance | BindingFlags.Public);
            if (field != null)
                return field.FieldType;
            var methods = viewModelType
                .GetMethods(BindingFlags.Instance | BindingFlags.Public)
                .Where(method => method.Name == name)
                .ToArray();
            if (methods.Length == 1 &&
                methods[0].ReturnType == typeof(void) &&
                !methods[0].IsGenericMethod &&
                methods[0].GetParameters().Length == 0)
                return typeof(Action);
            return null;
        }

        private static bool InferTarget(Type targetType, Type sourceType, out BindingTarget target)
        {
            if (typeof(Button).IsAssignableFrom(targetType) && typeof(ICommand).IsAssignableFrom(sourceType))
                return Found(BindingTarget.Command, out target);
            if (typeof(Button).IsAssignableFrom(targetType) && sourceType == typeof(Action))
                return Found(BindingTarget.Click, out target);
            if ((typeof(TMP_Text).IsAssignableFrom(targetType) || typeof(UnityEngine.UI.Text).IsAssignableFrom(targetType)) &&
                ObservableOf(sourceType, typeof(IReadOnlyObservableValue<>), typeof(string)))
                return Found(BindingTarget.Text, out target);
            if (typeof(Image).IsAssignableFrom(targetType) && ObservableOf(sourceType, typeof(IReadOnlyObservableValue<>), typeof(Sprite)))
                return Found(BindingTarget.Sprite, out target);
            if (typeof(Image).IsAssignableFrom(targetType) && ObservableOf(sourceType, typeof(IReadOnlyObservableValue<>), typeof(float)))
                return Found(BindingTarget.Fill, out target);
            if (typeof(Graphic).IsAssignableFrom(targetType) && ObservableOf(sourceType, typeof(IReadOnlyObservableValue<>), typeof(Color)))
                return Found(BindingTarget.Color, out target);
            if (typeof(GameObject).IsAssignableFrom(targetType) && ObservableOf(sourceType, typeof(IReadOnlyObservableValue<>), typeof(bool)))
                return Found(BindingTarget.Active, out target);
            if (typeof(CanvasGroup).IsAssignableFrom(targetType) && ObservableOf(sourceType, typeof(IReadOnlyObservableValue<>), typeof(bool)))
                return Found(BindingTarget.Visible, out target);
            if (typeof(Slider).IsAssignableFrom(targetType) && ObservableOf(sourceType, typeof(IObservableValue<>), typeof(float)))
                return Found(BindingTarget.Slider, out target);
            if (typeof(Scrollbar).IsAssignableFrom(targetType) && ObservableOf(sourceType, typeof(IObservableValue<>), typeof(float)))
                return Found(BindingTarget.Scrollbar, out target);
            if (typeof(Toggle).IsAssignableFrom(targetType) && ObservableOf(sourceType, typeof(IObservableValue<>), typeof(bool)))
                return Found(BindingTarget.Toggle, out target);
            if ((typeof(InputField).IsAssignableFrom(targetType) || typeof(TMP_InputField).IsAssignableFrom(targetType)) &&
                ObservableOf(sourceType, typeof(IObservableValue<>), typeof(string)))
                return Found(BindingTarget.Input, out target);
            if ((typeof(Dropdown).IsAssignableFrom(targetType) || typeof(TMP_Dropdown).IsAssignableFrom(targetType)) &&
                ObservableOf(sourceType, typeof(IObservableValue<>), typeof(int)))
                return Found(BindingTarget.Dropdown, out target);
            if (typeof(Selectable).IsAssignableFrom(targetType) && ObservableOf(sourceType, typeof(IReadOnlyObservableValue<>), typeof(bool)))
                return Found(BindingTarget.Interactable, out target);
            target = BindingTarget.Auto;
            return false;
        }

        private static bool Found(BindingTarget found, out BindingTarget target)
        {
            target = found;
            return true;
        }

        private static bool ValidTarget(Type targetType, Type sourceType, BindingTarget target)
        {
            switch (target)
            {
                case BindingTarget.Text:
                    return (typeof(TMP_Text).IsAssignableFrom(targetType) || typeof(UnityEngine.UI.Text).IsAssignableFrom(targetType)) &&
                           ObservableOf(sourceType, typeof(IReadOnlyObservableValue<>), typeof(string));
                case BindingTarget.Sprite:
                    return typeof(Image).IsAssignableFrom(targetType) &&
                           ObservableOf(sourceType, typeof(IReadOnlyObservableValue<>), typeof(Sprite));
                case BindingTarget.Color:
                    return typeof(Graphic).IsAssignableFrom(targetType) &&
                           ObservableOf(sourceType, typeof(IReadOnlyObservableValue<>), typeof(Color));
                case BindingTarget.Active:
                    return typeof(GameObject).IsAssignableFrom(targetType) &&
                           ObservableOf(sourceType, typeof(IReadOnlyObservableValue<>), typeof(bool));
                case BindingTarget.Visible:
                    return typeof(CanvasGroup).IsAssignableFrom(targetType) &&
                           ObservableOf(sourceType, typeof(IReadOnlyObservableValue<>), typeof(bool));
                case BindingTarget.Fill:
                    return typeof(Image).IsAssignableFrom(targetType) &&
                           ObservableOf(sourceType, typeof(IReadOnlyObservableValue<>), typeof(float));
                case BindingTarget.Interactable:
                    return typeof(Selectable).IsAssignableFrom(targetType) &&
                           ObservableOf(sourceType, typeof(IReadOnlyObservableValue<>), typeof(bool));
                case BindingTarget.Command:
                    return typeof(Button).IsAssignableFrom(targetType) && typeof(ICommand).IsAssignableFrom(sourceType);
                case BindingTarget.Click:
                    return typeof(Button).IsAssignableFrom(targetType) && sourceType == typeof(Action);
                case BindingTarget.Slider:
                    return typeof(Slider).IsAssignableFrom(targetType) &&
                           ObservableOf(sourceType, typeof(IObservableValue<>), typeof(float));
                case BindingTarget.Toggle:
                    return typeof(Toggle).IsAssignableFrom(targetType) &&
                           ObservableOf(sourceType, typeof(IObservableValue<>), typeof(bool));
                case BindingTarget.Input:
                    return (typeof(InputField).IsAssignableFrom(targetType) || typeof(TMP_InputField).IsAssignableFrom(targetType)) &&
                           ObservableOf(sourceType, typeof(IObservableValue<>), typeof(string));
                case BindingTarget.Dropdown:
                    return (typeof(Dropdown).IsAssignableFrom(targetType) || typeof(TMP_Dropdown).IsAssignableFrom(targetType)) &&
                           ObservableOf(sourceType, typeof(IObservableValue<>), typeof(int));
                case BindingTarget.Scrollbar:
                    return typeof(Scrollbar).IsAssignableFrom(targetType) &&
                           ObservableOf(sourceType, typeof(IObservableValue<>), typeof(float));
                default:
                    return false;
            }
        }

        private static bool ObservableOf(Type sourceType, Type contract, Type valueType)
        {
            if (sourceType.IsGenericType &&
                sourceType.GetGenericTypeDefinition() == contract &&
                sourceType.GetGenericArguments()[0] == valueType)
                return true;
            return sourceType.GetInterfaces().Any(candidate =>
                candidate.IsGenericType &&
                candidate.GetGenericTypeDefinition() == contract &&
                candidate.GetGenericArguments()[0] == valueType);
        }

        private static string Source(
            Type viewType,
            Type viewModelType,
            IReadOnlyCollection<(FieldInfo Field, BindAttribute Attribute, BindingTarget Target)> bindings,
            IReadOnlyCollection<(MethodInfo Method, string Source)> observations)
        {
            var code = new StringBuilder();
            code.AppendLine("// <auto-generated />");
            code.AppendLine(GeneratedOwner);
            code.AppendLine("using MvvmUnity.Unity;");
            code.AppendLine();
            if (!string.IsNullOrEmpty(viewType.Namespace))
            {
                code.Append("namespace ").AppendLine(viewType.Namespace);
                code.AppendLine("{");
            }

            var indent = string.IsNullOrEmpty(viewType.Namespace) ? string.Empty : "    ";
            code.Append(indent).Append(Accessibility(viewType)).Append(" partial class ").AppendLine(viewType.Name);
            code.Append(indent).AppendLine("{");
            code.Append(indent).AppendLine("    protected override void Bind(");
            code.Append(indent).AppendLine("        global::MvvmUnity.Unity.BindingScope bindings,");
            code.Append(indent).Append("        global::").Append(TypeName(viewModelType)).AppendLine(" viewModel)");
            code.Append(indent).AppendLine("    {");
            foreach (var binding in bindings)
            {
                code.Append(indent)
                    .Append("        bindings.").Append(binding.Target).Append('(')
                    .Append(binding.Field.Name).Append(", viewModel.")
                    .Append(binding.Attribute.Source).AppendLine(");");
            }
            foreach (var observation in observations)
            {
                code.Append(indent)
                    .Append("        bindings.Observe(viewModel.")
                    .Append(observation.Source).Append(", ")
                    .Append(observation.Method.Name).AppendLine(");");
            }
            code.Append(indent).AppendLine("        BindCustom(bindings, viewModel);");
            code.Append(indent).AppendLine("    }");
            code.Append(indent)
                .Append("    partial void BindCustom(global::MvvmUnity.Unity.BindingScope bindings, global::")
                .Append(TypeName(viewModelType)).AppendLine(" viewModel);");
            code.Append(indent).AppendLine("}");
            if (!string.IsNullOrEmpty(viewType.Namespace))
                code.AppendLine("}");
            return code.ToString();
        }

        private static string TypeName(Type type)
        {
            return type.FullName.Replace('+', '.');
        }

        private static string Accessibility(Type type)
        {
            return type.IsPublic ? "public" : "internal";
        }

        private static bool WriteWhenChanged(string path, string source)
        {
            if (File.Exists(path) && File.ReadAllText(path) == source)
                return false;
            Directory.CreateDirectory(Path.GetDirectoryName(path));
            File.WriteAllText(path, source, new UTF8Encoding(false));
            return true;
        }

        private static bool RemoveOrphans(IReadOnlyCollection<string> expected)
        {
            var changed = false;
            foreach (var path in GeneratedPaths())
            {
                if (!expected.Contains(path) && Owned(path))
                    changed |= AssetDatabase.DeleteAsset(path);
            }
            return changed;
        }

        private static IEnumerable<string> GeneratedPaths()
        {
            return AssetDatabase
                .FindAssets("t:MonoScript")
                .Select(AssetDatabase.GUIDToAssetPath)
                .Where(path => path.EndsWith(GeneratedSuffix, StringComparison.Ordinal));
        }

        private static bool Owned(string path)
        {
            using (var reader = File.OpenText(path))
            {
                reader.ReadLine();
                return reader.ReadLine() == GeneratedOwner;
            }
        }
    }
}
